nginx:
  image: nginx
  volumes:
    - nginx/conf.d:/etc/nginx/conf.d
    - nginx/certs:/etc/nginx/certs
  links:
    - wordpress:wordpress
  ports:
    - 80:80
    - 443:443
wordpress:
  image: ppschweiz/wordpress
  volumes:
    - wordpress:/var/www/html
  links:
    - mysql:mysql
  environment:
   WORDPRESS_DB_USER: root
   WORDPRESS_DB_PASSWORD: root
mysql:
  image: mysql
  volumes:
    - mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
